import Minutes from '@/models/Minutes';
import { format } from 'date-fns';

/**
 * Auto-create a Minutes-of-Meeting skeleton for a meeting. The mentor can later
 * edit and finalize it. Every meeting therefore always has a stored MoM record,
 * satisfying NAAC's requirement that minutes be maintained for all mentoring
 * activities.
 */
export async function autoGenerateMinutes(meeting, { attendees = [] } = {}) {
  const existing = await Minutes.findOne({ meeting: meeting._id });
  if (existing) return existing;

  const isParent = meeting.type === 'MONTHLY_PARENT';
  const agenda =
    meeting.agenda ||
    (isParent
      ? 'Review of academic performance, attendance, placements and mentoring feedback with parents.'
      : 'Review of academic progress, difficulties faced, guidance and action plan.');

  const doc = await Minutes.create({
    meeting: meeting._id,
    title: meeting.title,
    type: meeting.type,
    mentor: meeting.mentor,
    department: meeting.department,
    school: meeting.school,
    heldOn: meeting.scheduledAt,
    meetLink: meeting.meetLink,
    attendees,
    agenda,
    discussion:
      `Auto-generated draft for the ${isParent ? 'monthly parent' : 'weekly mentoring'} meeting held on ` +
      `${format(new Date(meeting.scheduledAt), 'dd MMM yyyy, hh:mm a')}. ` +
      `The mentor is requested to record the key points of discussion here.`,
    actionItems: [
      { item: 'Follow up on identified academic difficulties', owner: 'Mentor', status: 'OPEN' },
    ],
    decisions: '',
    nextMeetingOn: isParent
      ? new Date(new Date(meeting.scheduledAt).setMonth(new Date(meeting.scheduledAt).getMonth() + 1))
      : new Date(new Date(meeting.scheduledAt).getTime() + 7 * 24 * 60 * 60 * 1000),
    autoGenerated: true,
    finalized: false,
  });

  return doc;
}
