import mongoose from 'mongoose';

// Minutes of Meeting — auto-generated skeleton, editable by mentor, stored permanently.
const MinutesSchema = new mongoose.Schema(
  {
    meeting: { type: mongoose.Schema.Types.ObjectId, ref: 'Meeting', required: true, index: true },
    title: String,
    type: String,
    mentor: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    department: { type: mongoose.Schema.Types.ObjectId, ref: 'Department', index: true },
    school: { type: mongoose.Schema.Types.ObjectId, ref: 'School', index: true },
    heldOn: Date,
    meetLink: String,

    attendees: [{ name: String, role: String, email: String, present: Boolean }],
    agenda: String,
    discussion: String,
    actionItems: [{ item: String, owner: String, dueDate: Date, status: String }],
    decisions: String,
    nextMeetingOn: Date,

    autoGenerated: { type: Boolean, default: true },
    finalized: { type: Boolean, default: false },
    finalizedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

export default mongoose.models.Minutes || mongoose.model('Minutes', MinutesSchema);
